projectweb/pages/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from .views import registration, profile

app_name = 'pages'


urlpatterns = [
    path('about/', TemplateView.as_view(template_name='pages/about.html'),
         name='about'),
    path('rules/', TemplateView.as_view(template_name='pages/rules.html'),
         name='rules'),
    path('registr/', registration,
         name='registr'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'),
         name='login'),
    path('profile/', profile,
         name='profile'),
]

projectweb/projectweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web_inter.urls')),
    path('pages/', include('pages.urls', namespace='pages')),

]

projectweb/web_inter/urls.py
from django.urls import path

from . import views
from .views import PostUpdateView, PostDeleteView, PostCreateView, PostDetailView, PostListView, UserPostListView, \
    logout_view

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(template_name='pages/user_posts.html'), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(template_name='pages/post_detail.html'), name='post-detail'),
    path('post/new/', PostCreateView.as_view(template_name='pages/post_form.html'), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(template_name='pages/post_form.html'), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(template_name='pages/post_confirm_delete.html'), name='post-delete'),
    path('about/', views.about, name='blog-about'),
    path('logout/', logout_view, name='logout'),
]

projectweb/pages/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} Profile'

projectweb/web_inter/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

projectweb/pages/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class SignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

projectweb/pages/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import SignUpForm


# Create your views here.
def registration(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # получаем имя пользователя и пароль из формы
            username = form.cleaned_data.get('username')
            messages.success(request, f'Создан аккаунт {username}!')
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'registration/regist.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'registration/profile.html')

projectweb/web_inter/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Post

# Create your views here.

posts = [
]


def index(request):
    template = 'web_inter/index.html'
    return render(request, template)


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'web_inter/index.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'web_inter/index.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    success_url = '/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, 'pages/about.html', {'title': 'О клубе ChatSorr'})


class UserPostListView(ListView):
    model = Post
    template_name = 'pages/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


def logout_view(request):
    logout(request)
    return redirect('/')

projectweb/web_inter/templates/base_test.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Обязательные мета-теги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap, иконки и шрифт -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
     <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    {% if title %}
        <title>Блог клуба {{ title }}</title>
    {% else %}
        <title>Блог клуба ChatSorr</title>
    {% endif %}
</head>
<body>
    {% include "includes/header.html" %}
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
        	{% for message in messages %}
          	<div class="alert alert-{{ message.tags }}">
            	{{ message }}
          	</div>
        	{% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Разделы</h3>
            <p class='text-muted'>новости и события

            </p>
          </div>
        </div>
      </div>
    </main>
    <!-- Футер закреплен внизу, независимо от количества постов на странице -->
        {% include "includes/footer.html" %}
    <!-- Дополнительные скрипты JavaScript -->
    <!-- Сначала jQuery, затем Popper.js, последним Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

projectweb/web_inter/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <h3>© Chatsorr</h3>
</footer>

projectweb/web_inter/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-blue fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home' %}"><i class='bx bxs-rocket bx-tada-hover'></i> ChatSorr</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link " href="{% url 'blog-home' %}">Главная</a>
              <a class="nav-item nav-link" href="{% url 'pages:about' %}">О проекте</a>
              <a class="nav-item nav-link" href="{% url 'pages:rules' %}">Правила проекта</a>
            </div>
            <!-- Правая часть навигационной панели -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'post-create' %}">Новая запись</a>
              <a class="nav-item nav-link" href="{% url 'pages:profile' %}">Профиль</a>
              <a class="nav-item nav-link" href="{% url 'logout' %}">Выход</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'pages:login' %}">Вход</a>
              <a class="nav-item nav-link" href="{% url 'pages:registr' %}">Регистрация</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
{% endwith %}

projectweb/web_inter/templates/pages/about.html
{% extends "base_test.html" %}
{% block title %}
О проекте
{% endblock %}

{% block content %}
<div class="container py-5">
  <h1>О проекте</h1>
  <p>
    Блогикум — это дом для творческих людей. Это — сообщество людей, для которых
    нет грани между ведением блога и дружбой в социальных сетях.
  </p>
  <p>
    Дружба и рассказы о новых, неизведанных впечатлениях — вот
    что вы найдете на нашем ресурсе.  Миллионы блогов по различным темам.
    Путешествия, политики, развлечения, мода, мода, литература, дизайн и все
    другие сферы человеческой деятельности.
  </p>
  <p>
    Творчество, разнообразие и свобода взглядов и самовыражения —
    основные черты наших пользователей.
  </p>
</div>
{% endblock %}

projectweb/web_inter/templates/pages/post_confirm_delete.html
{% extends "base_test.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Удаление записи</legend>
                <h2>Вы уверены, что хотите удалить эту запись?"{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Да, хочу удалить</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Отмена</a>
            </div>
        </form>
    </div>
{% endblock content %}

projectweb/web_inter/templates/pages/post_detail.html
{% extends "base_test.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
       <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Редактировать</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Удалить</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}</p>
    </div>
  </article>
{% endblock content %}

projectweb/web_inter/templates/pages/post_form.html
{% extends "base_test.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Новая запись</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock content %}

projectweb/web_inter/templates/pages/rules.html
{% extends 'base_test.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="container py-5">
  <h1>Наши правила</h1>
  <p>
    <b>Cамовыражение.</b> У наших пользователей должна
    быть возможность создать что-то своё, выразить себя,
    свои мысли и чувства.
  </p>
  <p>
    <b>Многообразие.</b> Мы уважаем и приветствуем разные
    мнения и культуры. Блогикум — это место, объединяющее
    самых разных людей. Поделитесь своим уникальным взглядом на мир.
  </p>
  <p>
    <b>Творчество.</b> Не важно, в какой области вы творите,
    это может быть литература, дизайн, программирование.
    Наши инструменты помогут вам раскрыть талант максимально
    просто и комфортно.
  </p>
  <p>
    <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне.
    Делитесь своей информацией только с теми, кого выбрали.
    Как и насколько засекречивать вашу личную информацию —
    определяете вы и только вы.
  </p>
</div>
{% endblock %}

projectweb/web_inter/templates/pages/user_posts.html
{% extends "base_test.html" %}
{% block content %}
    <h1 class="mb-3">Записи пользователя {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <div class="pagination justify-content-center"> 
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4 mr-1" href="?page=1">Первая</a>
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
      {% endif %}

    {% endif %}
  </div>
{% endblock content %}

projectweb/web_inter/templates/web_inter/index.html
{% extends 'base_test.html' %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
           <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <div class="pagination justify-content-center">
    {% if is_paginated %}

      {% if page_obj.has_previous %}

        <a class="btn btn-outline-info mb-4 mr-1" href="?page=1">Первая</a>
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
      {% endif %}

    {% endif %}
  </div>
{% endblock content %}